# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Joseph
email: chrisjosephsongs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a musician, physicist, coder and. I studied astronomy, physics and vinyl records in school and now work as a software developer in the field of audio. This is my personal website and blog, I mainly talk about music, science, my latest software projects and audio. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cjmusic.github.io/" # the base hostname & protocol for your site
twitter_username: chrisjoseph95
github_username:  cjmusic

# Build settings
markdown: kramdown
